### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by W5ALC** [SudoMakeMeASandwichDE/unipkg#1]
I tried to run on 3 different systems (Termux for Android, Fedora, Arch) none had a config file.

unipkg update
Error while trying to read configuration file: [Errno 2] No such file or directory: '/home/XXXXXxXxx/.config/unipkg/unipkg.conf'

unipkg update
Error while trying to read configuration file: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.config/unipkg/unipkg.conf'

What may be missing to either create the file or have it come with a default config

**Comment by SudoMakeMeASandwichDE** [comment]
Thanks for posting this issue, I just fixed it and it should work now. Try it and say if it works for you too now! :)

**Comment by W5ALC** [comment]
Still not working on termux or my arch install. that's going to be something on my end though as termux is kind of obscure and the arch installarion is very specialized distro for a specific purpose, something on my end.

However, confirmed working on Fedora (dnf).

Error on termux

Broken configuration file. Reconfiguration required.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/unipkg.py", line 56, in main
    vars.configuration[0] = ast.literal_eval(vars.configuration[0])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 112, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 92, in _convert
    return list(map(_convert, node.elts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 111, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 85, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 76, in _convert_num
    _raise_malformed_node(node)
  File "/data/data/com.termux/files/usr/lib/python3.12/ast.py", line 73, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Name object at 0x6f2144d250>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/unipkg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/unipkg.py", line 59, in main
    settings()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/src/settings.py", line 7, in settings
    if len(vars.pms) > 1:
       ^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()

Termux uses a script that calls apt fpr package management so I probably wont be able to uae it there. Which is fine I have a few pm scripts that allow me to do what I need.

All in all I encountered some issues on my end which you [probably] wont be able to address but when it works it works well.

**Comment by SudoMakeMeASandwichDE** [comment]
Thanks for the update and confirmation that it works on Fedora! Since the remaining issues seem to be related to specific setups on your end, I'll go ahead and close this issue. Feel free to report any issues you encounter in the future.
